<a href="https://colab.research.google.com/github/Kushagraraghav/python_code/blob/main/4thapril2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]
list3 = [11, 12, 13, 14, 15]
arr = np.array([list1, list2, list3])
print(arr[1:2,1:3])
print("Original array:")
print(arr)
new_row = [20, 21, 22, 23, 24]
arr = np.insert(arr, 1, new_row, axis=0)
print("\nAfter inserting values:")
print(arr)
print(arr.reshape(2,10))
print(arr[1:2,1:3])
print(arr[ :1 ,3 :])

[[7 8]]
Original array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

After inserting values:
[[ 1  2  3  4  5]
 [20 21 22 23 24]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3  4  5 20 21 22 23 24]
 [ 6  7  8  9 10 11 12 13 14 15]]
[[21 22]]
[[4 5]]


In [17]:
arr =np.random.randint(0,100,20).reshape(4,5)
print(arr)
print(arr[1:3,1:4])

[[ 5 26 64 25 61]
 [16 81 95 30 60]
 [95 33 71 65 58]
 [ 6 63 47 13 50]]
[[81 95 30]
 [33 71 65]]


In [18]:
arr = np.arange(0,20,2).reshape(2,5)
print(arr)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [29]:
import pandas as pd
import numpy as np

arr = pd.DataFrame(data=np.arange(0, 25).reshape(5, 5), index=["A", "B", "C", "D", "E"], columns=["K", "U", "S", "H", "A"])
arr.head()
arr.describe()



K          U          S          H          A
count   5.000000   5.000000   5.000000   5.000000   5.000000
mean   10.000000  11.000000  12.000000  13.000000  14.000000
std     7.905694   7.905694   7.905694   7.905694   7.905694
min     0.000000   1.000000   2.000000   3.000000   4.000000
25%     5.000000   6.000000   7.000000   8.000000   9.000000
50%    10.000000  11.000000  12.000000  13.000000  14.000000
75%    15.000000  16.000000  17.000000  18.000000  19.000000
max    20.000000  21.000000  22.000000  23.000000  24.000000